### ISSUE TITLE
Add note on unit testing on GitLab to lab4

### ISSUE THREAD

**Issue by janfrancu** [JuliaTeachingCTU/Scientific-Programming-in-Julia#37]
Unit test can be setup also on GitLab, see [tutorial](https://tamaspapp.eu/post/julia-ci-gitlab/) from Tamás K. Papp. 
It boils down to adding a file `.gitlab-ci.yml` to the root of a repo with the following few lines
```yaml
image: julia:1.6                # image comes from Docker hub

default:
  script:
    - julia --project=@. -e "import Pkg; Pkg.test()"
```
Documentation can be hosted in a similar fashion as well.
